# Generated by Django 4.0.2 on 2022-02-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_choice_question_questionchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(related_name='questions', to='polls.Choice'),
        ),
        migrations.DeleteModel(
            name='QuestionChoice',
        ),
    ]
