# Generated by Django 4.0.2 on 2022-02-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_question_choices_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='questions',
            field=models.ManyToManyField(to='polls.Question'),
        ),
    ]
